#!/bin/bash

PERCENT=$(acpi | awk '{print $4}' | sed 's/,//g' | sed 's/%//g')
REMAIN=$(acpi | grep -o -E "[0-9]+:[0-9]+:[0-9]+")

notify-send "Remaining Time" "$REMAIN"

if [ $PERCENT -le 15 ]; then
    notify-send "🪫 Low Battery" "Plug the charger"
fi
