#!/bin/sh

main() {
    if [ "$1" = "-g" ] && [ "$2" = "-s" ]; then
        dict -d fd-deu-eng $3 | awk '(NR>4)'

    elif [ "$1" = "-g" ] && [ "$2" = "-f" ]; then
        while read word
        do
            dict -d fd-deu-eng $word | awk '(NR>4)' >> $3_out.txt
        done < $3

    elif [ "$1" = "-d" ] && [ "$2" = "-s" ]; then
        dict -d wn $3 | awk '(NR>4)'

    elif [ "$1" = "-d" ] && [ "$2" = "-f" ]; then
        while read word
        do
            dict -d wn $word | awk '(NR>4)' >> $3_out.txt
        done < $3

    elif [ "$1" = "-t" ] && [ "$2" = "-s" ]; then
        dict -d moby-thesaurus $3 | awk '(NR>4)'

    elif [ "$1" = "-t" ] && [ "$2" = "-f" ]; then
        while read word
        do
            dict -d moby-thesaurus $word | awk '(NR>4)' >> $3_out.txt
        done < $3

    elif [ "$1" = "-e" ] && [ "$2" = "-s" ]; then
        dict -d elements $2 | awk '(NR>4)'

    elif [ "$1" = "-h" ]; then
        echo "Usage: $0 [-g|-d|-t] [-s|-f] [word|file]"
        echo "  -g: German-English dictionary"
        echo "  -d: English dictionary"
        echo "  -t: English thesaurus"
        echo "  -e: Look up the definition of a chemical element"
        echo "  -s: Single object"
        echo "  -f: File with words"
    fi
}

main "$@"
