#!/bin/sh
echo "Enter Your Document Name: "
read name 
notify-send "LaTeX Document Created!"
cd ~/Documents/Notes/
mkdir "$name"
cp ~/Documents/Notes/Templates/LT.tex  ~/Documents/Notes/"$name"/"$name.tex"
nvim ~/Documents/Notes/"$name"/"$name.tex"
