#!/bin/bash

player_status=$(playerctl --player rhythmbox status 2> /dev/null)
# stats= 

if [[ $? -eq 0 ]]; then
    metadata="$(playerctl --player rhythmbox metadata artist) - $(playerctl --player rhythmbox metadata title)  $(playerctl --player rhythmbox metadata -f "{{emoji(status)}}")"
fi

# Foreground color formatting tags are optional
if [[ $player_status = "Playing" ]]; then
    echo "%{F#FFFFFF}$metadata%{F-}"
elif [[ $player_status = "Paused" ]]; then
    echo "%{F#999}$metadata%{F-}"
else
    echo ""
fi
