#!/bin/sh

echo "Enter Your Document Name: "
read name
notify-send "Markdown Document Created!"
cd /home/core/Documents/Obsidian/Broadest\ Education/1\ -\ Inbox/
touch "$name"
cp ~/Documents/Notes/Templates/article.md /home/core/Documents/Obsidian/Broadest\ Education/1\ -\ Inbox/"$name.md"
nvim /home/core/Documents/Obsidian/Broadest\ Education/1\ -\ Inbox/"$name.md"



