#!/bin/sh

echo "Enter Your Presentation Name: "
read name 
notify-send "Presentation Created!"

mkdir ~/Documents/60\ -\ Notes/"$name"
cd ~/Documents/60\ -\ Notes/"$name"

cp ~/Documents/60\ -\ Notes/Templates/presentation.tex  ~/Documents/60\ -\ Notes/"$name"/"$name.tex"
nvim ~/Documents/60\ -\ Notes/"$name"/"$name.tex"

