#!/bin/sh

echo "Enter Your Presentation Name: "
read name 
notify-send "Presentation Created!"

mkdir ~/Documents/Notes/"$name"
cd ~/Documents/Notes/"$name"

cp ~/Documents/Notes/Templates/presentation.tex  ~/Documents/Notes/"$name"/"$name.tex"
nvim ~/Documents/Notes/"$name"/"$name.tex"

