#!/bin/sh

echo "Enter Your Exercise Name: "
read name
notify-send "Python File Created!"
cd /home/core/Documents/Programming/Course\ Exercises/
touch "$name.py"
nvim //home/core/Documents/Programming/Course\ Exercises/"$name.py"



