#!/bin/sh

echo "Enter Your Document Name: "
read name 
notify-send "LaTeX Document Created!"

mkdir ~/Documents/Notes/"$name"
cd ~/Documents/Notes/"$name"

cp ~/Documents/Notes/Templates/LT.tex  ~/Documents/Notes/"$name"/"$name.tex"
nvim ~/Documents/Notes/"$name"/"$name.tex"

