#!/bin/sh
if [ "$(xset -q | grep -A 0 'LED' | cut -c59-67)" = '00000000' ] 
  then
  notify-send 'Current Keyboard Layout:' 'US (English)'
fi
if [ "$(xset -q | grep -A 0 'LED' | cut -c59-67)" = '00001000' ]
  then
  notify-send 'Current Keyboard Layout:' 'IR (Persian)'
fi
