#!/bin/sh

echo "Enter Your Document Name: "
read name
notify-send "Rmarkdown Document Created!"
cd ~/Documents/Notes/
mkdir "$name"
cp ~/Documents/Notes/Templates/rmark.rmd ~/Documents/Notes/"$name"/"$name.rmd"
vim ~/Documents/Notes/"$name"/"$name.rmd"


